model:
  sequence_length: 20
  prediction_horizon: 5
  lstm_units: 64
  dropout_rate: 0.3

training:
  epochs: 50
  batch_size: 64
  validation_split: 0.15
  test_split: 0.15
  early_stopping_patience: 10
  lr_reduction_factor: 0.5
  lr_patience: 5
  min_lr: 0.0001
  random_seed: 42 